plugins:

    cloudify_plugin_existing_server:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            url: https://github.com/ilyash/cloudify-plugin-existing-server/archive/master.zip

    cloudify_plugin_puppet:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/Fewbytes/cloudify-plugin-puppet/archive/master.zip
            # folder: cloudify-plugin-puppet

imports:
    - cloudify.openstack
    - existing-server-type.yaml
    - puppet-type.yaml

blueprint:
    name: existing-server-test
    nodes:
        # -
        #     name: existing_server
        #     type: existing_server
        #     properties:
        #         ip: 10.67.79.222
        #         install_agent: true
        #         worker_config:
        #             port: 22
        #             user: ubuntu
        #             key: ~/.ssh/cloudify-agents-kp-ilya.pem
        -
            name: server
            type: cloudify.openstack.server
            properties:
                install_agent: true
                worker_config:
                    port: 22
                    user: ubuntu
                    key: ~/.ssh/cloudify-agents-kp-ilya.pem
                management_network_name: cloudify-admin-network
                server:
                    name: ilya-puppet-client
                    image_name: Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)
                    flavor_name: standard.small  # 2G RAM, 2 CPUs
                    key_name: cloudify-agents-kp-ilya
                    security_groups: [cloudify-sg-agents]
                    userdata: |
                        #!/bin/bash -ex
                        grep -q puppet /etc/hosts || echo "15.126.234.172 puppet" >> /etc/hosts
        -
            name: puppet_node_one
            type: db_server_puppet
            properties:
                puppet_config:
                    add_operation_tag: True,
                    operations_tags:
                        create: [op_tag_create, tag2]
                    environment: e1
                    tags: [a, b]
                    server: puppet
                    node_name_prefix: pfx-
                    node_name_suffix: .puppet.example.com
            relationships:
                -
                    type: cloudify.relationships.contained_in
                    # target: existing_server
                    target: server
